In [1]:
import numpy as np
from utils import get_data, check_results

In [22]:
def calculate_iou(gt_bbox, pred_bbox):
    """
    calculate iou 
    args:
    - gt_bbox [array]: 1x4 single gt bbox
    - pred_bbox [array]: 1x4 single pred bbox
    returns:
    - iou [float]: iou between 2 bboxes
    """
    xmin = np.max([gt_bbox[0], pred_bbox[0]])
    ymin = np.max([gt_bbox[1], pred_bbox[1]])
    xmax = np.min([gt_bbox[2], pred_bbox[2]])
    ymax = np.min([gt_bbox[3], pred_bbox[3]])
    
    intersection = max(0, xmax - xmin + 1) * max(0, ymax - ymin + 1)
    gt_area = (gt_bbox[2] - gt_bbox[0]) * (gt_bbox[3] - gt_bbox[1])
    pred_area = (pred_bbox[2] - pred_bbox[0]) * (pred_bbox[3] - pred_bbox[1])
    
    union = gt_area + pred_area - intersection
    return intersection / union


def calculate_ious(gt_bboxes, pred_bboxes):
    """
    calculate ious between 2 sets of bboxes 
    args:
    - gt_bboxes [array]: Nx4 ground truth array
    - pred_bboxes [array]: Mx4 pred array
    returns:
    - iou [array]: NxM array of ious
    """
    ious = np.zeros((gt_bboxes.shape[0], pred_bboxes.shape[0]))
    for i, gt_bbox in enumerate(gt_bboxes):
        for j, pred_bbox in enumerate(pred_bboxes):
            ious[i,j] = calculate_iou(gt_bbox, pred_bbox)
    return ious

In [15]:
ground_truth, predictions = get_data()

In [16]:
ground_truth[0]

{'boxes': [[576, 545, 617, 584],
  [551, 628, 573, 651],
  [508, 437, 646, 552],
  [584, 1021, 679, 1057],
  [521, 716, 627, 756],
  [550, 711, 600, 729],
  [586, 558, 630, 617],
  [614, 76, 653, 105],
  [567, 910, 598, 927],
  [604, 1188, 826, 1244],
  [561, 542, 579, 563],
  [557, 654, 583, 684],
  [589, 1190, 655, 1240],
  [562, 559, 578, 578],
  [603, 1723, 857, 1821],
  [578, 881, 686, 923],
  [586, 942, 671, 971],
  [581, 996, 661, 1023],
  [597, 1105, 761, 1250],
  [586, 625, 646, 703],
  [558, 892, 589, 908],
  [593, 907, 684, 941],
  [577, 987, 650, 1014],
  [569, 1593, 613, 1613],
  [577, 1109, 665, 1129],
  [560, 942, 601, 963],
  [574, 1107, 665, 1149],
  [525, 321, 682, 466],
  [599, 1151, 809, 1206],
  [560, 608, 594, 642],
  [581, 512, 639, 537],
  [538, 685, 577, 706],
  [541, 543, 581, 591],
  [611, 94, 671, 123],
  [582, 1069, 681, 1110],
  [562, 900, 604, 918],
  [588, 1723, 900, 1872],
  [557, 870, 608, 883],
  [565, 956, 633, 983],
  [644, 0, 912, 192],
  [545, 643

In [17]:
predictions[0]

{'boxes': [[783, 1104, 1011, 1700],
  [853, 0, 1220, 200],
  [734, 0, 1100, 240],
  [753, 474, 868, 609],
  [830, 1500, 1004, 1914]],
 'classes': [1, 2, 1, 2, 1],
 'filename': 'segment-1231623110026745648_480_000_500_000_with_camera_labels_38.png'}

In [18]:
filename = 'segment-1231623110026745648_480_000_500_000_with_camera_labels_38.png'

In [19]:
gt_bboxes = [g['boxes'] for g in ground_truth if g['filename'] == filename][0]
gt_bboxes = np.array(gt_bboxes)
gt_bboxes

array([[ 793, 1134, 1001, 1718],
       [ 737,    0,  898,  260],
       [ 763,  484,  878,  619],
       [ 734,    0, 1114,  277],
       [ 853,    0, 1280,  250],
       [ 820, 1566,  974, 1914],
       [ 762,  951,  844, 1175],
       [ 748,  197,  803,  363]])

In [20]:
pred_bboxes = [p['boxes'] for p in predictions if p['filename'] == filename][0]
pred_boxes = np.array(pred_bboxes)
pred_boxes

array([[ 783, 1104, 1011, 1700],
       [ 853,    0, 1220,  200],
       [ 734,    0, 1100,  240],
       [ 753,  474,  868,  609],
       [ 830, 1500, 1004, 1914]])

In [23]:
ious = calculate_ious(gt_bboxes, pred_boxes)
ious

array([[0.85341754, 0.        , 0.        , 0.        , 0.24170945],
       [0.        , 0.0872149 , 0.43065146, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.75483215, 0.        ],
       [0.        , 0.41795902, 0.84514539, 0.        , 0.        ],
       [0.        , 0.69661525, 0.44331044, 0.        , 0.        ],
       [0.12414345, 0.        , 0.        , 0.        , 0.67452648],
       [0.02980132, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.02607242, 0.        , 0.        ]])

In [24]:
check_results(ious)

AssertionError: The iou calculation is wrong!

In [25]:
np.load('./data/exercise1_check.npy')

array([[0.84313051, 0.        , 0.        , 0.        , 0.23860974],
       [0.        , 0.08469791, 0.4243356 , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.73221757, 0.        ],
       [0.        , 0.41277874, 0.83450504, 0.        , 0.        ],
       [0.        , 0.68758782, 0.43810509, 0.        , 0.        ],
       [0.12221933, 0.        , 0.        , 0.        , 0.66359447],
       [0.02888778, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.02499868, 0.        , 0.        ]])