In [1]:
import numpy as np

from iou import calculate_ious
from utils import get_data

In [2]:
def precision_recall(ious, gt_classes, pred_classes):
    """
    calculate precision and recall
    args:
    - ious [array]: NxM array of ious
    - gt_classes [array]: 1xN array of ground truth classes
    - pred_classes [array]: 1xM array of pred classes
    returns:
    - precision [float]
    - recall [float]
    """
    xs, ys = np.where(ious>0.5)

    # calculate true positive and true negative
    tps = 0
    fps = 0
    for x, y in zip(xs, ys):
        if gt_classes[x] == pred_classes[y]:
            tps += 1
        else:
            fps += 1

    matched_gt = len(np.unique(xs))
    fns = len(gt_classes) - matched_gt

    precision = tps / (tps+fps)
    recall = tps / (tps + fns)
    return precision, recall

In [3]:
ground_truth, predictions = get_data()

In [4]:
ground_truth[0]

{'boxes': [[576, 545, 617, 584],
  [551, 628, 573, 651],
  [508, 437, 646, 552],
  [584, 1021, 679, 1057],
  [521, 716, 627, 756],
  [550, 711, 600, 729],
  [586, 558, 630, 617],
  [614, 76, 653, 105],
  [567, 910, 598, 927],
  [604, 1188, 826, 1244],
  [561, 542, 579, 563],
  [557, 654, 583, 684],
  [589, 1190, 655, 1240],
  [562, 559, 578, 578],
  [603, 1723, 857, 1821],
  [578, 881, 686, 923],
  [586, 942, 671, 971],
  [581, 996, 661, 1023],
  [597, 1105, 761, 1250],
  [586, 625, 646, 703],
  [558, 892, 589, 908],
  [593, 907, 684, 941],
  [577, 987, 650, 1014],
  [569, 1593, 613, 1613],
  [577, 1109, 665, 1129],
  [560, 942, 601, 963],
  [574, 1107, 665, 1149],
  [525, 321, 682, 466],
  [599, 1151, 809, 1206],
  [560, 608, 594, 642],
  [581, 512, 639, 537],
  [538, 685, 577, 706],
  [541, 543, 581, 591],
  [611, 94, 671, 123],
  [582, 1069, 681, 1110],
  [562, 900, 604, 918],
  [588, 1723, 900, 1872],
  [557, 870, 608, 883],
  [565, 956, 633, 983],
  [644, 0, 912, 192],
  [545, 643

In [5]:
predictions[0]

{'boxes': [[783, 1104, 1011, 1700],
  [853, 0, 1220, 200],
  [734, 0, 1100, 240],
  [753, 474, 868, 609],
  [830, 1500, 1004, 1914]],
 'classes': [1, 2, 1, 2, 1],
 'filename': 'segment-1231623110026745648_480_000_500_000_with_camera_labels_38.png'}

In [6]:
filename = 'segment-1231623110026745648_480_000_500_000_with_camera_labels_38.png'

In [9]:
gt_bboxes = [g['boxes'] for g in ground_truth if g['filename'] == filename][0]
gt_bboxes = np.array(gt_bboxes)
gt_bboxes

array([[ 793, 1134, 1001, 1718],
       [ 737,    0,  898,  260],
       [ 763,  484,  878,  619],
       [ 734,    0, 1114,  277],
       [ 853,    0, 1280,  250],
       [ 820, 1566,  974, 1914],
       [ 762,  951,  844, 1175],
       [ 748,  197,  803,  363]])

In [8]:
gt_classes = [g['classes'] for g in ground_truth if g['filename'] == filename][0]
gt_classes

[1, 1, 1, 1, 2, 1, 1, 1]

In [10]:
pred_bboxes = [p['boxes'] for p in predictions if p['filename'] == filename][0]
pred_boxes = np.array(pred_bboxes)
pred_boxes

array([[ 783, 1104, 1011, 1700],
       [ 853,    0, 1220,  200],
       [ 734,    0, 1100,  240],
       [ 753,  474,  868,  609],
       [ 830, 1500, 1004, 1914]])

In [11]:
pred_classes = [p['classes'] for p in predictions if p['filename'] == filename][0]
pred_classes

[1, 2, 1, 2, 1]

In [12]:
ious = calculate_ious(gt_bboxes, pred_boxes)
ious

array([[0.84313051, 0.        , 0.        , 0.        , 0.23860974],
       [0.        , 0.08469791, 0.4243356 , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.73221757, 0.        ],
       [0.        , 0.41277874, 0.83450504, 0.        , 0.        ],
       [0.        , 0.68758782, 0.43810509, 0.        , 0.        ],
       [0.12221933, 0.        , 0.        , 0.        , 0.66359447],
       [0.02888778, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.02499868, 0.        , 0.        ]])

In [13]:
precision, recall = precision_recall(ious, gt_classes, pred_classes)

In [15]:
recall

0.5714285714285714

In [14]:
precision

0.8